"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelTypes = exports.Events = exports.Permissions = void 0;
var Permissions;
(function (Permissions) {
    Permissions["CREATE_INSTANT_INVITE"] = "createInstantInvite";
    Permissions["KICK_MEMBERS"] = "kickMembers";
    Permissions["BAN_MEMBERS"] = "banMembers";
    Permissions["ADMINISTRATOR"] = "administrator";
    Permissions["MANAGE_CHANNELS"] = "manageChannels";
    Permissions["MANAGE_GUILD"] = "manageGuild";
    Permissions["ADD_REACTIONS"] = "addReactions";
    Permissions["VIEW_AUDIT_LOG"] = "viewAuditLogs";
    Permissions["PRIORITY_SPEAKER"] = "voicePrioritySpeaker";
    Permissions["STREAM"] = "stream";
    Permissions["VIEW_CHANNEL"] = "readMessages";
    Permissions["SEND_MESSAGES"] = "sendMessages";
    Permissions["SEND_TTS_MESSAGES"] = "sendTTSMessages";
    Permissions["MANAGE_MESSAGES"] = "manageMessages";
    Permissions["EMBED_LINKS"] = "embedLinks";
    Permissions["ATTACH_FILES"] = "attachFiles";
    Permissions["READ_MESSAGE_HISTORY"] = "readMessageHistory";
    Permissions["MENTION_EVERYONE"] = "mentionEveryone";
    Permissions["USE_EXTERNAL_EMOJIS"] = "externalEmojis";
    Permissions["VIEW_GUILD_INSIGHTS"] = "viewGuildInsights";
    Permissions["CONNECT"] = "voiceConnect";
    Permissions["SPEAK"] = "voiceSpeak";
    Permissions["MUTE_MEMBERS"] = "voiceMuteMembers";
    Permissions["DEAFEN_MEMBERS"] = "voiceDeafenMembers";
    Permissions["MOVE_MEMBERS"] = "voiceMoveMembers";
    Permissions["USE_VAD"] = "voiceUseVAD";
    Permissions["CHANGE_NICKNAME"] = "changeNickname";
    Permissions["MANAGE_NICKNAMES"] = "manageNicknames";
    Permissions["MANAGE_ROLES"] = "manageRoles";
    Permissions["MANAGE_WEBHOOKS"] = "manageWebhooks";
    Permissions["MANAGE_EMOJIS"] = "manageEmojis";
    Permissions["ALL"] = "all";
    Permissions["ALL_GUILD"] = "allGuild";
    Permissions["ALL_TEXT"] = "allText";
    Permissions["ALL_VOICE"] = "allVoice";
})(Permissions = exports.Permissions || (exports.Permissions = {}));
var Events;
(function (Events) {
    Events["CALL_CREATE"] = "callCreate";
    Events["CALL_DELETE"] = "callDelete";
    Events["CALL_UPDATE"] = "callUpdate";
    Events["CHANNEL_CREATE"] = "channelCreate";
    Events["CHANNEL_DELETE"] = "channelDelete";
    Events["CHANNEL_PIN_UPDATE"] = "channelPinUpdate";
    Events["CHANNEL_RECIPIENT_ADD"] = "channelRecipientAdd";
    Events["CHANNEL_RECIPIENT_REMOVE"] = "channelRecipientRemove";
    Events["CHANNEL_UPDATE"] = "channelUpdate";
    Events["CONNECT"] = "connect";
    Events["DEBUG"] = "debug";
    Events["DISCONNECT"] = "disconnect";
    Events["ERROR"] = "error";
    Events["FRIEND_SUGGESTION_CREATE"] = "friendSuggestionCreate";
    Events["FRIEND_SUGGESTION_DELETE"] = "friendSuggestionDelete";
    Events["GUILD_VAILABLE"] = "guildAvailable";
    Events["GUILD_BAN_ADD"] = "guildBanAdd";
    Events["GUILD_BAN_REMOVE"] = "guildBanRemove";
    Events["GUILD_CREATE"] = "guildCreate";
    Events["GUILD_DELETE"] = "guildDelete";
    Events["GUILD_EMOJIS_UPDATE"] = "guildEmojisUpdate";
    Events["GUILD_MEMBER_ADD"] = "guildMemberAdd";
    Events["GUILD_MEMBER_CHUNK"] = "guildMemberChunk";
    Events["GUILD_MEMBER_REMOVE"] = "guildMemberRemove";
    Events["GUILD_ROLE_CREATE"] = "guildRoleCreate";
    Events["GUILD_ROLE_DELETE"] = "guildRoleDelete";
    Events["GUILD_ROLE_UPDATE"] = "guildRoleUpdate";
    Events["GUILD_UNAVAILABLE"] = "guildUnavailable";
    Events["GUILD_UPDATE"] = "guildUpdate";
    Events["HELLO"] = "hello";
    Events["INVITE_CREATE"] = "inviteCreate";
    Events["INVITE_DELETE"] = "inviteDelete";
    Events["MESSAGE_CREATE"] = "messageCreate";
    Events["MESSAGE_DELETE"] = "messageDelete";
    Events["MESSAGE_DELETE_BULK"] = "messageDeleteBulk";
    Events["MESSAGE_REACTION_ADD"] = "messageReactionAdd";
    Events["MESSAGE_REACTION_REMOVE"] = "messageReactionRemove";
    Events["MESSAGE_REACTION_REMOVE_ALL"] = "messageReactionRemoveAll";
    Events["MESSAGE_REACTION_REMOVE_EMOJI"] = "messageReactionRemoveEmoji";
    Events["MESSAGE_UPDATE"] = "messageUpdate";
    Events["PRESENCE_UPDATE"] = "presenceUpdate";
    Events["RAW_REST"] = "rawREST";
    Events["RAW_WS"] = "rawWS";
    Events["READY"] = "ready";
    Events["RELATIONSHIP_ADD"] = "relationshipAdd";
    Events["RELATIONSHIP_REMOVE"] = "relationshipRemove";
    Events["RELATIONSHIP_UPDATE"] = "relationshipUpdate";
    Events["SHARD_DISCONNECT"] = "shardDisconnect";
    Events["SHARD_PRE_READY"] = "shardPreReady";
    Events["SHARD_READY"] = "shardReady";
    Events["SHARD_RESUME"] = "shardResume";
    Events["TYPING_START"] = "typingStart";
    Events["UNAVAILABLE_GUILD_CREATE"] = "unavailableGuildCreate";
    Events["UNKNOWN"] = "unknown";
    Events["USER_UPDATE"] = "userUpdate";
    Events["VOICE_CHANNEL_JOIN"] = "voiceChannelJoin";
    Events["VOICE_CHANNEL_LEAVE"] = "voiceChannelLeave";
    Events["VOICE_CHANNEL_SWITCH"] = "voiceChannelSwitch";
    Events["VOICE_STATE_UPDATE"] = "voiceStateUpdate";
    Events["WARN"] = "warn";
    Events["WEBHOOKS_UPDATE"] = "webhooksUpdate";
})(Events = exports.Events || (exports.Events = {}));
var ChannelTypes;
(function (ChannelTypes) {
    ChannelTypes[ChannelTypes["GUILD_TEXT"] = 0] = "GUILD_TEXT";
    ChannelTypes[ChannelTypes["GUILD_NEWS"] = 5] = "GUILD_NEWS";
    ChannelTypes[ChannelTypes["DM"] = 1] = "DM";
    ChannelTypes[ChannelTypes["GROUP_DM"] = 3] = "GROUP_DM";
})(ChannelTypes = exports.ChannelTypes || (exports.ChannelTypes = {}));
//# sourceMappingURL=constants.js.map